version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ApiToSQS"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-u0fscug1va48"
s3_prefix = "ApiToSQS"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"Dev\" MainStackName=\"StackSqs\" SQSName=\"MySqsQueue\""
image_repositories = []
